### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by lukeramsden** [danielchalmers/SteamAccountSwitcher#13]
Would be nice to have different sections to organize accounts.

**Comment by danielchalmers** [comment]
How do you mean?

One possible way of keeping accounts separate at the moment is creating a few copies of the portable exe with different names and enabling `Allow multiple instances` on each of them, because settings are kept per path.

**Comment by lukeramsden** [comment]
Something kinda like this:

![mockup](https://i.imgur.com/tIAkZBI.png)

with a title and whatever.

**Comment by danielchalmers** [comment]
Separators?  
I like the idea, though I think it adds too much complexity (mostly internally). Maybe a fork would be better?

[Here's a quick version I made to play around with (with a few conflict features disabled).](https://github.com/danielchalmers/SteamAccountSwitcher/files/1552888/SteamAccountSwitcher.2.3.with.Separators.zip)
