### ISSUE TITLE
add option to remember password

### ISSUE THREAD

**Issue by gameplanetworld** [danielchalmers/SteamAccountSwitcher#16]
it can be nice if there is an option to activate the "remember password" option in steam automaticly. when you are closing steam from time to time or restart your pc it will be nice to not have to put in the steam gaurd code over and over again.

**Comment by danielchalmers** [comment]
i redesigned the way it logs in and that should no longer be an issue. please check out [version 3]([version 3](https://github.com/danielchalmers/SteamAccountSwitcher/releases)) and let me know if it works for you! @gameplanetworld
