### ISSUE TITLE
It doesn't work anymore with the new Steam update

### ISSUE THREAD

**Issue by moslem1056** [danielchalmers/SteamAccountSwitcher#17]
It doesn't work anymore with the new Steam update

Update the app to work with the new Steam update

Wednesday - 2022 12 October

**Comment by danielchalmers** [comment]
Is it still broken with the new [v3.0.0-beta1](https://github.com/danielchalmers/SteamAccountSwitcher/releases/tag/v3.0.0-beta1)? @moslem1056

**Comment by danielchalmers** [comment]
Is this still an issue?
