### ISSUE TITLE
Not working on latest windows build

### ISSUE THREAD

**Issue by icyglacial** [danielchalmers/SteamAccountSwitcher#21]
can you kindly take a look, the app not working since i update to build 19045.2673 (22h2)

got The instruction at 0x00007ffe2d4c0522 referenced memory at 0x00000000. The memory could not be read. Click on OK to terminate the program everytime i open. am i missing something

**Comment by danielchalmers** [comment]
Weird. I got the same update and am having no issues so far.

Could you try reinstalling the app and restarting your PC and see if that changes anything?
